package slapdconf

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"time"

	ldap "github.com/go-ldap/ldap/v3"
	"github.com/go-ldap/ldif"
)

// OpenLDAP is an opt-in external test oracle, never a conversion dependency.
func TestOpenLDAPConversionOracle(t *testing.T) {
	if os.Getenv("LDAP_GO_SLAPDCONF_ORACLE") != "1" {
		t.Skip("set LDAP_GO_SLAPDCONF_ORACLE=1 to compare with external OpenLDAP tools")
	}
	slaptest, err := exec.LookPath("slaptest")
	if err != nil {
		t.Fatal(err)
	}
	slapcat, err := exec.LookPath("slapcat")
	if err != nil {
		t.Fatal(err)
	}
	schemaPath := os.Getenv("LDAP_GO_OPENLDAP_SCHEMA_DIR")
	slapadd, err := exec.LookPath("slapadd")
	if err != nil {
		t.Fatal(err)
	}
	if schemaPath == "" {
		for _, candidate := range []string{"/etc/ldap/schema", "/etc/openldap/schema", "/opt/homebrew/etc/openldap/schema"} {
			if _, err := os.Stat(filepath.Join(candidate, "core.schema")); err == nil {
				schemaPath = candidate
				break
			}
		}
	}
	if schemaPath == "" {
		t.Fatal("set LDAP_GO_OPENLDAP_SCHEMA_DIR to an OpenLDAP schema directory")
	}
	base := t.TempDir()
	configDir := filepath.Join(base, "slapd.d")
	dataDir := filepath.Join(base, "data")
	for _, path := range []string{configDir, dataDir} {
		if err := os.Mkdir(path, 0o700); err != nil {
			t.Fatal(err)
		}
	}
	path := configFile(t, fmt.Sprintf(`include %q
backend mdb
database config
rootdn cn=config
rootpw "config secret"
database mdb
suffix dc=example,dc=com
rootdn "cn=Directory Manager,dc=example,dc=com"
rootpw " password with \"quote\" and \\ slash"
directory %q
maxsize 10485760
index objectClass eq
index cn eq,sub
access to attrs=userPassword by self write by anonymous auth by * none
access to * by * read
overlay syncprov
syncprov-checkpoint 100 10
syncprov-sessionlog 50
`, filepath.Join(schemaPath, "core.schema"), dataDir))
	ctx, cancel := context.WithTimeout(t.Context(), 20*time.Second)
	defer cancel()
	initialize := exec.CommandContext(ctx, slapadd, "-f", path, "-n", "1")
	initialize.Stdin = strings.NewReader("")
	if output, err := initialize.CombinedOutput(); err != nil {
		t.Fatalf("initialize oracle database: %v\n%s", err, output)
	}
	if output, err := exec.CommandContext(ctx, slaptest, "-f", path, "-F", configDir).CombinedOutput(); err != nil {
		t.Fatalf("slaptest: %v\n%s", err, output)
	}
	export := exec.CommandContext(ctx, slapcat, "-F", configDir, "-n", "0")
	var stderr bytes.Buffer
	export.Stderr = &stderr
	output, err := export.Output()
	if err != nil {
		t.Fatalf("slapcat: %v\n%s", err, &stderr)
	}
	oracle := map[string]*ldap.Entry{}
	for record, err := range ldif.UnmarshalEntries(bytes.NewReader(output), &ldif.LDIF{}) {
		if err != nil {
			t.Fatal(err)
		}
		oracle[strings.ToLower(record.Entry.DN)] = record.Entry
	}
	document, err := ConvertFile(path, ParseOptions{})
	if err != nil {
		t.Fatal(err)
	}
	goConfigDir := filepath.Join(base, "go-slapd.d")
	if err := os.Mkdir(goConfigDir, 0o700); err != nil {
		t.Fatal(err)
	}
	var generated bytes.Buffer
	if err := document.WriteLDIF(&generated); err != nil {
		t.Fatal(err)
	}
	importGo := exec.CommandContext(ctx, slapadd, "-F", goConfigDir, "-n", "0")
	importGo.Stdin = &generated
	if output, err := importGo.CombinedOutput(); err != nil {
		t.Fatalf("OpenLDAP rejected Go LDIF: %v\n%s", err, output)
	}
	for _, check := range []struct{ dn, attribute string }{
		{"olcDatabase={0}config,cn=config", "olcRootPW"},
		{"olcDatabase={1}mdb,cn=config", "olcRootDN"},
		{"olcDatabase={1}mdb,cn=config", "olcRootPW"},
		{"olcDatabase={1}mdb,cn=config", "olcSuffix"},
		{"olcDatabase={1}mdb,cn=config", "olcDbDirectory"},
		{"olcDatabase={1}mdb,cn=config", "olcDbIndex"},
		{"olcOverlay={0}syncprov,olcDatabase={1}mdb,cn=config", "olcSpCheckpoint"},
		{"olcOverlay={0}syncprov,olcDatabase={1}mdb,cn=config", "olcSpSessionlog"},
	} {
		entry := oracle[strings.ToLower(check.dn)]
		if entry == nil {
			t.Fatalf("oracle missing %s", check.dn)
		}
		got := values(t, document, check.dn, check.attribute)
		want := entry.GetEqualFoldAttributeValues(check.attribute)
		if !reflect.DeepEqual(got, want) {
			t.Errorf("%s %s: Go=%q OpenLDAP=%q", check.dn, check.attribute, got, want)
		}
	}
}
